modLoader = "javafml"
loaderVersion = "*"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/fantahund/Voxelmap/issues"

[[mods]]
modId = "voxelmap"
version = "${version}"
displayName = "Voxelmap"
logoFile = "icon.png"
authors = "Lahwran, Zaneris, MamiyaOtaru, fantahund, Brokkonaut, TheAlgorithm476"
description = "Minimap and world map"
displayURL = "https://github.com/fantahund/Voxelmap"

[[dependencies.voxelmap]]
modId = "forge"
mandatory = true
versionRange = "[47,48)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.voxelmap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "mixin.voxelmap.json"

[[mixins]]
config = "mixin.voxelmap.forge.json"