modLoader = "javafml"
loaderVersion = "*"
license = "All Rights Reserved"

[[mods]]
modId = "lightmap"
version = "${version}"
displayName = "LightMap"
logoFile = "icon.png"
description = "Minimap and world map"

[[dependencies.lightmap]]
modId = "forge"
mandatory = true
versionRange = "[47,48)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lightmap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "mixin.lightmap.json"

[[mixins]]
config = "mixin.lightmap.forge.json"
